BEGIN
  FOR c IN (SELECT CUSTOMERID, BALANCE FROM CUSTOMERS) LOOP
    IF c.BALANCE >= 100000 THEN
      UPDATE CUSTOMERS
      SET STATUS = 'VIP',
          LASTMODIFIED = SYSDATE
      WHERE CUSTOMERID = c.CUSTOMERID;
    END IF;
  END LOOP;

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('VIP status updated based on balance.');
END;
/